apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rocky
  name: rocky
spec:
  replicas: 10
  selector:
    matchLabels:
      app: rocky
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rocky
    spec:
      containers:
      - image: petyb/rocky:3
        name: rocky
