apiVersion: v1
kind: Service
metadata:
  labels:
    app: rocky
  name: rocky-np
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    app: rocky
  type: NodePort
